
const subgenre = {
    cozy: "Cozy Mystery",
    dark: "Bloody Mystery",
    supernatural: "Supernatural Mystery",
    classic: "Classic Detective",
    kids: "YA & Kid Mystery",
    historical: "Historical Mystery"
};

const BooksData = [
    {
        id: 1,
        title: "Detection Unlimited",
        author: "Supernatural Mystery", 
        cover: "/assets/book/book_1.jpg", 
        rating: 3.8,
        subgenre: subgenre.dark,
        published_year: "1971",
        price: "$8.39",
        description: "Only Hemingway can uncover which of the ten has turned hatred into murder, but has his work cut out for him.",
    },
    {
        id: 2,
        title: "The Mysterious Island",
        author: "Jules Verne", 
        cover: "/assets/book/book_2.jpg", 
        rating: 3.9,
        subgenre: subgenre.cozy,
        published_year: "1977",
        price: "9.99",
        description: "The Mysterious Island tells the tale of five Americans who, in an attempt to escape the Civil War, pilot a hot-air balloon and find themselves crashed on a deserted island somewhere in the Pacific.",
    },
    {
        id: 3,
        title: "Sherlock Holmes",
        author: "Conan Doyle", 
        cover: "/assets/book/book_3.jpg", 
        rating: 4.8,
        subgenre: subgenre.classic,
        published_year: "1924",
        price: "$15.99",
        description: "A man is found dead in an abandoned house in the heart of one of London's most sinister districts. Traces of blood are scattered around him, though the corpse shows no signs of injury.",
    },
    {
        id: 4,
        title: "The Mystery of the Blue Train",
        author: "Agatha Christie", 
        cover: "/assets/book/book_4.png", 
        rating: 4.1,
        subgenre: subgenre.historical,
        published_year: "2024",
        price: "$7.50",
        description: "When she takes them with her on a luxury train to the Riviera, she is unaware that among her fellow passengers are her unfaithful husband and the famous retired detective Hercule Poirot, possibly, a murderer.",
    },
    {
        id: 5,
        title: "Murder in Three Acts",
        author: "Agatha Christie", 
        cover: "/assets/book/book_5.png", 
        rating: 3.7,
        subgenre: subgenre.dark,
        published_year: "1984",
        price: "$9.40",
        description: "For at the end of the evening one of them is dead—choked by a cocktail that contained no trace of poison.",
    },
    {d
        id: 6,
        title: "Space Case",
        author: "Stuart Gibbs", 
        cover: "/assets/book/book_6.png", 
        rating: 5.0,
        subgenre: subgenre.cozy,
        published_year: "1998",
        price: "$7.60",
        description: "",
    },
    {
        id: 7,
        title: "The Mystery of the Green Ghost",
        author: "Robert Arthur", 
        cover: "/assets/book/book_7.png", 
        rating: 3.8,
        subgenre: subgenre.supernatural,
        published_year: "1980",
        price: "$11.00",
        description: "The Three Investigators become entangled in the theft of a string of rare pearls and a fraudulent scheme involving family inheritance when they try to solve the mystery of a ghost's appearance in the old Green Mansion.",
    },
    {
        id: 8,
        title: "Emil and the Detectives",
        author: "Erich Kästner", 
        cover: "/assets/book/book_8.png", 
        rating: 4.4,
        subgenre: subgenre.kids,
        published_year: "1930",
        price: "$5.30",
        description: "On his first real train journey, travelling down to his grandmother in Berlin, Emil Tischbein is robbed of all his money. Emil gathers together a group of boys of his own age and sets out on the trail of the thief. ",
    },
    {
        id: 9,
        title: "Murder Most Unladylike",
        author: "Robin Stevens", 
        cover: "/assets/book/book_9.png", 
        rating: 4.2,
        subgenre: subgenre.classic,
        published_year: "2016",
        price: "$19.55",
        description: "Hazel Wong and Daisy Wells struggle to find an exciting mystery to investigate and hit pay-dirt when Hazel discovers the dead body of Miss Bell, the science teacher.",
    },
    {
        id: 10,
        title: "Clue At The Bottom Of The Lake",
        author: "Kristiana Gregory", 
        cover: "/assets/book/book_10.png", 
        rating: 4.0,
        subgenre: subgenre.kids,
        published_year: "2023",
        price: "$5.64",
        description: "When twelve year old Jeff Bridger spots a shadowy figure drop something in the lake, he and his younger brother David, and their cousin Claire investigate and discover a duffel bag full of stolen artifacts, and try to find out who is behind the theft.",
    },
    {
        id: 11,
        title: "New Detective",
        author: "Peter Steiner", 
        cover: "/assets/book/book_11.png", 
        rating: 2.8,
        subgenre: subgenre.classic,
        published_year: "2023",
        price: "$19.05",
        description: "Willi confronts a grotesque scientific theory and a dangerous ideology taking root in society that could lead him to a killer, but there are those who are just as determined to stop him in his tracks...",
    },
    {
        id: 12,
        title: "Girl in the White Van",
        author: "April Henry", 
        cover: "/assets/book/book_12.png", 
        rating: 4.8,
        subgenre: subgenre.dark,
        published_year: "2021",
        price: "$6.50",
        description: "When Savannah disappears soon after arguing with her mom's boyfriend, everyone assumes she's run away. The truth is much worse. ",
    },
    {
        id: 13,
        title: "The Green Mile",
        author: "Stephen King", 
        cover: "/assets/book/book_13.png", 
        rating: 4.3,
        subgenre: subgenre.supernatural,
        published_year: "1999",
        price: "$20.66",
        description: "The Green Mile is a 1996 serial novel by American writer Stephen King. It tells the story of death row supervisor Paul Edgecombe's encounter with John Coffey, an unusual inmate who displays inexplicable healing and empathetic abilities.",
    },
    {
        id: 14,
        title: "The Sign of the Four",
        author: "Arthur Conan Doyle", 
        cover: "/assets/book/book_14.png", 
        rating: 4.3,
        subgenre: subgenre.historical,
        published_year: "2018",
        price: "$2.55",
        description: "When a young lady approaches Sherlock Holmes looking for help in finding out what happened to her father when he disappeared 10 years earlier.",
    },
    {
        id: 15,
        title: "A Study in Scarlet",
        author: "Arthur Conan Doyle", 
        cover: "/assets/book/book_15.png", 
        rating: 4.0,
        subgenre: subgenre.historical,
        published_year: "2018",
        price: "$3.10",
        description: "The body of a man has been found in an abandoned house, without wounds or other marks of injury. But on the wall, scrawled in blood, is the word RACHE. The subsequent unravelling of the mystery takes many unexpected turns.",
    },
    {
        id: 16,
        title: "The Case of the Missing Marquess",
        author: "Nancy Springer", 
        cover: "/assets/book/book_16.png", 
        rating: 4.4,
        subgenre: subgenre.kids,
        published_year: "2006",
        price: "$7.30",
        description: "When Enola Holmes, sister to the detective Sherlock Holmes, discovers her mother has disappeared, she quickly embarks on a journey to London in search of her.",
    },
    {
        id: 17,
        title: "The Prom Queen",
        author: "Robert Lawrence Stine", 
        cover: "/assets/book/book_17.png", 
        rating: 4.3,
        subgenre: subgenre.supernatural,
        published_year: "1992",
        price: "$5.96",
        description: "Lizzie McVay was so excited to be nominated Prom Queen. But when the other candidates are murdered, Lizzie must uncover the killer's identity before it's too late.",
    },
    {
        id: 18,
        title: "Poached",
        author: "Stuart Gibbs", 
        cover: "/assets/book/book_18.png", 
        rating: 5.0,
        subgenre: subgenre.cozy,
        published_year: "2014",
        price: "$5.35",
        description: "Teddy is the only person caught on camera entering and exiting the exhibit. Teddy didn't commit the crime--but if he can't find the real culprit, he'll be sent to juvie as a convicted koala-napper.",
    }
]
