
const BooksData = [
    {
        id: 1,
        title: "Detection Unlimited",
        author: "Georgette Heyer", 
        cover: "/assets/book/book-1.jpg", 
        rating: 3.8,
        subgenre: "subgenre 3",
        published_date: "1971-09-05",
        price: "$8.39",
    },
    {
        id: 2,
        title: "The Mysterious Island",
        author: "Jules Verne", 
        cover: "/assets/book/book-2.jpg", 
        rating: 3.9,
        subgenre: "subgenre 2",
        published_year: "1977-01-13",
        price: "9.99",
    },
    {
        id: 3,
        title: "Sherlock Holmes",
        author: "Conan Doyle", 
        cover: "/assets/book/book-3.jpg", 
        rating: 4.8,
        subgenre: "subgenre 1",
        published_year: "1924-05-12",
        price: "$15.99",
    },
    {
        id: 4,
        title: "The Mystery of the Blue Train",
        author: "Agatha Christie", 
        cover: "/assets/book/book-4.png", 
        rating: 4.1,
        subgenre: "subgenre 1",
        published_year: "2024-05-12",
        price: "$15.99",
    },
    {
        id: 5,
        title: "Murder in Three Acts",
        author: "Agatha Christie", 
        cover: "/assets/book/book-5.png", 
        rating: 3.7,
        subgenre: "subgenre 2",
        published_year: "1984-05-12",
        price: "$7.40",
    },
    {
        id: 6,
        title: "The Mysterious Cargo",
        author: "Galila Ben-Uri", 
        cover: "/assets/book/book-6.png", 
        rating: 3.2,
        subgenre: "subgenre 2",
        published_year: "1989",
        price: "$19.40",
    },
    {
        id: 7,
        title: "The Mystery of the Green Ghost",
        author: "Robert Arthur", 
        cover: "/assets/book/book-7.png", 
        rating: 4.0,
        subgenre: "subgenre 4",
        published_year: "1980",
        price: "$19.40",
    },
]